version: 0.2

env:
  variables:
    HUGO_VERSION: "0.49.1"
    S3_BUCKETNAME: "dovetail.io"

phases:
  install:
    commands:
      - echo Installing required packages and Hugo
      - apt-get update
      - apt-get install -y git golang wget curl sed
      - wget -q https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_Linux-64bit.deb -O /tmp/hugo.dep
      - dpkg -i /tmp/hugo.dep
  pre_build:
    commands:
      - mkdir -p ${CODEBUILD_SRC_DIR}/dovetail-contrib/
      - mv ${CODEBUILD_SRC_DIR_contrib}/* ${CODEBUILD_SRC_DIR}/dovetail-contrib/
  build:
    commands:
      - echo Build started on `date`
      - echo Update Documentation
      - cd ${CODEBUILD_SRC_DIR} && sh ./build-docs.sh magic
  post_build:
    commands:
      - echo Build completed on `date`
#artifacts:
#  files:
#    - /opt/app/docs/public/**/*